### Numpyarray
numpy는 행렬 계산할 때 편함

In [2]:
import numpy

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
list_2=[2,4,6,8,10]

In [5]:
list_1+list_2

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [7]:
array1=numpy.array((list_1,list_2))

In [15]:
array2=numpy.array(list_2)

In [10]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [13]:
[list_1[i]+list_2[i] for i in range (5)]

[3, 6, 9, 12, 15]

In [22]:
array1.shape

array([ 2,  4,  6,  8, 10])

In [20]:
array1.size

(5,)

In [15]:
array3=numpy.random.random(6)

In [16]:
array3

array([0.73590775, 0.33272623, 0.69961325, 0.26432874, 0.69456044,
       0.84269469])

In [17]:
import numpy as np

In [18]:
array1=np.full(6,0)
array1

array([0, 0, 0, 0, 0, 0])

In [19]:
array2=np.zeros(6)

In [20]:
array2

array([0., 0., 0., 0., 0., 0.])

### numpy2

In [21]:
array1=np.array([2,3,4,5,6,7,8,9,10])

In [22]:
array1[-1]

10

In [23]:
array1[-1:]

array([10])

In [24]:
list_4=[]

In [25]:
list_4[-1:]

[]

In [26]:
array1[2::2]

array([ 4,  6,  8, 10])

In [27]:
array1*2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
array1=np.array([1000,2000,3000,5000])
#환율

booleans 가능

In [31]:
import pandas as pd

In [32]:
score = [['song',50,86],['choi',89,31],['hwang',68,91],['Lee',88,75]]

In [39]:
df = pd.DataFrame(score, columns=['name','math score','Eng score'],index=['a','b','c','d'])
df

name  math score  Eng score
a   song          50         86
b   choi          89         31
c  hwang          68         91
d    Lee          88         75

In [40]:
type(df)

pandas.core.frame.DataFrame

In [41]:
df.columns

Index(['name', 'math score', 'Eng score'], dtype='object')

In [42]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
df.dtypes

name          object
math score     int64
Eng score      int64
dtype: object

In [44]:
import numpy as np
import pandas as pd

In [47]:
#score
score_list=score
score_array=np.array(score)
list_of_series=[
    pd.Series(['song',50,86]),
    pd.Series(['choi',89,31]),
    pd.Series(['hwang',68,91]),
    pd.Series(['Lee',88,75])
]

In [48]:
df1=pd.DataFrame(score_list)#list형
df2=pd.DataFrame(score_array)#numpy형으로 할 수도 있고
df3=pd.DataFrame(list_of_series)#Series가 여러개 모이면 core임

print(df1)
print(df2)
print(df3)

       0   1   2
0   song  50  86
1   choi  89  31
2  hwang  68  91
3    Lee  88  75
       0   1   2
0   song  50  86
1   choi  89  31
2  hwang  68  91
3    Lee  88  75
       0   1   2
0   song  50  86
1   choi  89  31
2  hwang  68  91
3    Lee  88  75


In [51]:
names = ['song','choi','hwang','Lee']
math_scores=[50,89,68,88]
eng_scores=[86,31,91,75]

In [53]:
dic1={
    'names':names,
    'english score':eng_scores,
    'math score' :math_scores
}

dic2={
    'names':np.array(names),
    'english score':np.array(eng_scores),
    'math score' :np.array(math_scores)
}

dic3={
    'names':pd.Series(names),
    'english socre':pd.Series(eng_scores),
    'math score':pd.Series(math_scores),

}

In [55]:
df1=pd.DataFrame(dic1)
df2=pd.DataFrame(dic2)
df3=pd.DataFrame(dic3)

In [57]:
print(df1)
print(df2)
print(df3)

   names  english score  math score
0   song             86          50
1   choi             31          89
2  hwang             91          68
3    Lee             75          88
   names  english score  math score
0   song             86          50
1   choi             31          89
2  hwang             91          68
3    Lee             75          88
   names  english socre  math score
0   song             86          50
1   choi             31          89
2  hwang             91          68
3    Lee             75          88


In [58]:
score_list

[['song', 50, 86], ['choi', 89, 31], ['hwang', 68, 91], ['Lee', 88, 75]]

In [65]:
df=pd.DataFrame(score_list,columns=['name','eng_score','math_score'])
df

name  eng_score  math_score
0   song         50          86
1   choi         89          31
2  hwang         68          91
3    Lee         88          75

### pandas 2

In [66]:
import pandas as pd

In [78]:
laptops_df=pd.read_csv('laptops.csv')
laptops_df

brand             model  ram hd_type  hd_size  screen_size   price  \
0     Dell  Inspiron 15-3567    4     hdd     1024         15.6   40000   
1    Apple       MacBook Air    8     ssd      128         13.3   55499   
2    Apple       MacBook Air    8     ssd      256         13.3   71500   
3    Apple       MacBook Pro    8     ssd      128         13.3   96890   
4    Apple       MacBook Pro    8     ssd      256         13.3  112666   
..     ...               ...  ...     ...      ...          ...     ...   
162   Asus            A555LF    8     hdd     1024         15.6   39961   
163   Asus     X555LA-XX172D    4     hdd      500         15.6   28489   
164   Asus            X554LD    2     hdd      500         15.6   29199   
165   Asus    X550LAV-XX771D    2     hdd      500         15.6   29990   
166   Asus     X540LA-XX538T    4     hdd     1024         15.6   30899   

    processor_brand processor_model  clock_speed graphic_card_brand  \
0             intel              i5          2.5              intel   
1             intel              i5          1.8              intel   
2             intel              i5          1.8              intel   
3             intel              i5          2.3              intel   
4             intel              i5          2.3              intel   
..              ...             ...          ...                ...   
162           intel      i3 4th gen          1.7             nvidia   
163           intel      i3 4th gen          1.9              intel   
164           intel      i3 4th gen          1.9              intel   
165           intel      i3 4th gen          1.7              intel   
166           intel      i3 5th gen          2.0              intel   

     graphic_card_size       os  weight comments  
0                  NaN    linux    2.50      NaN  
1                  2.0      mac    1.35      NaN  
2                  2.0      mac    1.35      NaN  
3                  2.0      mac    3.02      NaN  
4                  2.0      mac    3.02      NaN  
..                 ...      ...     ...      ...  
162                2.0  windows    2.30      NaN  
163                NaN    linux    2.30      NaN  
164                1.0    linux    2.30      NaN  
165                NaN    linux    2.50      NaN  
166                NaN  windows    2.30      NaN  

[167 rows x 15 columns]

In [77]:
iphone_df=pd.read_csv('iphone.csv',index_col=0)
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes