In [1]:
import numpy as np

In [4]:
A = np.array([
    [1,-1,2],
    [3,4,5],
    [6,7,8]
])
A

array([[ 1, -1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [5]:
B= np.random.rand(3,5)
B

array([[0.48937339, 0.93522568, 0.95509261, 0.78803862, 0.23789554],
       [0.9550591 , 0.86176704, 0.71754753, 0.5986068 , 0.15763453],
       [0.88188321, 0.17152254, 0.95249974, 0.64632384, 0.20012085]])

In [6]:
C=np.zeros((2,4))
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
type(A)

numpy.ndarray

In [8]:
A[0][2]

2

In [13]:
B=np.array([
    [1,2,3],
    [-5,3,1],
    [2,3,8]
])
B

array([[ 1,  2,  3],
       [-5,  3,  1],
       [ 2,  3,  8]])

In [12]:
A*B

array([[  1,  -2,   6],
       [-15,  12,   5],
       [ 12,  21,  64]])

In [14]:
A+B

array([[ 2,  1,  5],
       [-2,  7,  6],
       [ 8, 10, 16]])

In [15]:
A@B#행렬간의 곱셈은 @을 사용한다. 

array([[ 10,   5,  18],
       [ -7,  33,  53],
       [-13,  57,  89]])

In [16]:
A_transpose=np.transpose(A)
A_transpose

array([[ 1,  3,  6],
       [-1,  4,  7],
       [ 2,  5,  8]])

In [17]:
A

array([[ 1, -1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [18]:
A.T

array([[ 1,  3,  6],
       [-1,  4,  7],
       [ 2,  5,  8]])

In [19]:
A

array([[ 1, -1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [20]:
I = np.identity(4)#단위 행렬
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
A_inverse =np.linalg.pinv(A)
A_inverse

array([[ 0.2       , -1.46666667,  0.86666667],
       [-0.4       ,  0.26666667, -0.06666667],
       [ 0.2       ,  0.86666667, -0.46666667]])

In [22]:
A@A_inverse

array([[ 1.00000000e+00,  2.22044605e-15, -1.33226763e-15],
       [ 3.33066907e-16,  1.00000000e+00,  4.44089210e-16],
       [ 6.66133815e-16, -2.66453526e-15,  1.00000000e+00]])

## 선형회귀
Linear regression

y=ax+b

평균
분산
표준편차

## 손실 함수 
### (실제 값- 예측값)을 이용해서 표준편차를 구하는 거
### 표준편차가 작으면 평균에 가까움

### 오차 = 실제 값 - 예측값